version: "3.7"

services:
  app:
    user: $MY_USER_ID:$GID
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app:Z
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
